version: '3'
services:
    postgres-db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        expose:
            - 5432
        networks:
            - mern-app
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}',
                ]
            interval: 5s
            timeout: 5s
            retries: 10
networks:
    mern-app:
        driver: bridge
